### PR TITLE
put the result in searchresult.html

### PR DESCRIPTION
**Pull request by Ythyang**
Realize the search results jump to another page

### CODE REVIEW

**Review by ConnorCoull — CHANGES_REQUESTED** [review]
Where are you using pyexpat? You didn't delete the print statements in the searchresults view. There is still an if statement but it needs both. Why did you delete the formatting for the title_block? you shouldn't have touched that. You referenced the pk field incorrectly, you decided to delete a closing tag? Why? What is going on with line 31? why have you called book instead of book.book_title? did you check the models before this was coded? Overall make sure the formatting is consistent please and make sure you understand what you're adding and why.

**Comment by Ythyang** [comment]
Since there is no user in url.py, it has to be #. Missing ID for book in URL

**Review by ConnorCoull — COMMENTED** [review]
Show me it working where it returns nothing in either, results only in book, results only in user and results in both, then I will accept. Make sure you have accounted for merge conflicts.

**Comment by Ythyang** [comment]
If either users_list or book_list is available, the book link is displayed. If either is not available, No Users /books match your query is displayed

**Review by ConnorCoull — CHANGES_REQUESTED** [review]
I still do not see the </ul> you deleted it on line 23 and it hasn't been added back

**Review by ConnorCoull — APPROVED** [review]

**Pull request merged**
