### PR TITLE
Fixed the error you mentioned

### PR DESCRIPTION
**Pull request by StudentChenyu**

### CODE REVIEW

**Review by ConnorCoull — COMMENTED** [review]
On hold until main issue can be dealt with.

**Review by ConnorCoull — CHANGES_REQUESTED** [review]
Upload book takes the user to the login page? As a title? this should just be plain text "Add Book" or something similar. why change from btn_primary to btn_success?

**Comment by StudentChenyu** [comment]
> Upload book takes the user to the login page? As a title? this should just be plain text "Add Book" or something similar. why change from btn_primary to btn_success?

This code means that if a visitor tries to access AddBook without logging in, it will lead the visitor is returned to the login page .
And for btn, you are right, I should not change it.

**Review by ConnorCoull — CHANGES_REQUESTED** [review]
I may be wrong on this so please double check but I think if current user auth should be in body block, endblock should also be the last tag (currently it is the if block) the code looks correct it's just in the wrong order.

**Review by ConnorCoull — APPROVED** [review]
Looks correct to me.

**Pull request merged**
