### PR TITLE
Add login restriction.

### PR DESCRIPTION
**Pull request by StudentChenyu**
I have tested it. Everything is ok.

### CODE REVIEW

**Review by ConnorCoull — CHANGES_REQUESTED** [review]
rejected

**Review by ConnorCoull — CHANGES_REQUESTED** [review]
not sure what you're trying to do in settings, but just revert it back if it doesn't work, your code is really messy and comments are a part of that, I'm not sure why you have a single list element, again with the commented out code. to be clear, you are pushing to main, this is the final version, there shouldn't be code this messy.

**Comment by StudentChenyu** [comment]
Done

**Review by ConnorCoull — CHANGES_REQUESTED** [review]
pull latest version

**Pull request closed without merging**
