### PR TITLE
Finished Upload Function... ...

### PR DESCRIPTION
**Pull request by StudentChenyu**
Please check it.

### CODE REVIEW

**Review by ConnorCoull — CHANGES_REQUESTED** [review]
<b>forms.py</b>
<ul>
<li>forms.Form -> forms.ModelForm</li>
</ul>
<br />
<b>migrations/0006.....</b>
<ul>
<li>this should not be here</li>
</ul>
<br />
<b>views.py</b>
<ul>
<li>pull the latest version please, I have said this plenty of times</li>
</ul>
<br />

**Comment by StudentChenyu** [comment]
> forms.py
> 
>     * forms.Form -> forms.ModelForm
> 
> 
> 
> migrations/0006.....
> 
>     * this should not be here
> 
> 
> 
> views.py
> 
>     * pull the latest version please, I have said this plenty of times

but if I use 'forms.ModelForm', the cmd will throw error....

**Comment by StudentChenyu** [comment]
Done, I pulled the latest version and modified it according to your requirements.
And... sorry about I forgot pull latest version....

**Review by ConnorCoull — COMMENTED** [review]
Please show functionality of it working as intended and I will let changes through.

**Comment by StudentChenyu** [comment]
Apply again, demo video is here, (here is a problem, I do not know why the system will report error after upload file...) 

and here is demonstrate video: https://gla-my.sharepoint.com/:v:/g/personal/2612988z_student_gla_ac_uk/Ed4CiXJTihFIh6UBAWOson8B93OW6lGr1AnWORP-GembAg?e=mcTT4r

and:
1. I uploaded a html file, it is probably the most basic template, if it's not good then I'll delete it.   
2. In model.py I added a few lines of code to keep my functionality running. Now I commented it out. If I want to modify the model.py file, I have to contact Mark, right?  
3. The same is true in url.py.  I commented out my own testing code.. so that makes anyone who reads these commits understands what they do.(maybe)

**Review by ConnorCoull — CHANGES_REQUESTED** [review]
The function should work before you try and push it, I can't allow code that broken to join main, (there is clearly a significant error if the operation does not work)

**Comment by StudentChenyu** [comment]
> The function should work before you try and push it, I can't allow code that broken to join main, (there is clearly a significant error if the operation does not work)

Sure.

**Review by ConnorCoull — APPROVED** [review]
Needs to make sure that the book is linked to an author, hope the lack of userauth doesn't cause any damage

**Pull request merged**
